sonar.organization=alexismetton
sonar.projectKey=AlexisMetton_kubesecurebox_landing_page

sonar.sources=.
sonar.exclusions=.git/**,.github/**,**/node_modules/**,*.min.js,Dockerfile,nginx.conf,.dockerignore
